name: Deploy to Azure Static Web App
on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'  # Location of your application source code
          api_location: ''    # Location of your API source code, if any
          output_location: '/'  # Location of your build output

